<?php echo $this->getChildHtml('store_switcher'); ?>
<?php if(count($this->getStores())>1): ?>
<div class="form-language easyflags-hidden">
    <?php if(Mage::helper('easyflags')->isLableLangSwitcherEnabled()): ?>
    <label for="select-language"><?php echo $this->__('Your Language:') ?></label>
    <?php endif; ?>
    <select id="select-language" title="<?php echo $this->__('Your Language') ?>" class="easyflags-select" onchange="window.location.href=this.value" >
    <?php foreach ($this->getStores() as $_lang): ?>
        <?php $flagSrc = Mage::helper('easyflags')->getImageUrl($_lang); ?>
        <?php $_selected = ($_lang->getId() == $this->getCurrentStoreId()) ? ' selected="selected"' : '' ?>
        <option value="<?php echo $_lang->getCurrentUrl() ?>"<?php echo $_selected ?> data-image-url="<?php echo $flagSrc; ?>">
            <?php echo $this->escapeHtml($_lang->getName()) ?>
        </option>
    <?php endforeach; ?>
    </select>
</div>
<?php endif; ?>
