<?php if(count($this->getStores())>1): ?>
    <div class="form-language" id="easyflags">
        <?php foreach ($this->getStores() as $_lang): ?>
            <?php $img = Mage::helper('easyflags')->getImageUrl($_lang); ?>
            <a href="<?php echo $_lang->getCurrentUrl() ?>">
                <img src="<?php echo $img ?>" alt="<?php echo $this->htmlEscape($_lang->getName()) ?>"/>
            </a>
        <?php endforeach; ?>
    </div>
<?php endif; ?>
