<?php if(count($this->getStores())>1): ?>
<?php
    $classes = 'eflags-inline';
    if (Mage::getStoreConfig('easy_flags/store_switcher/move')) {
        $classes .= ' eflags-stores-moved';
    }
?>
<div class="store-switcher <?php echo $classes;?>">
    <?php if(Mage::helper('easyflags')->isLableStoreSwitcherEnabled()): ?>
    <span class="eflags-label"><?php echo $this->__('Select Store:') ?></span>
    <?php endif; ?>
    <?php foreach ($this->getGroups() as $_group): ?>
        <?php $flagSrc = Mage::helper('easyflags')->getImageUrl($_group); ?>
        <?php $storeName = $this->htmlEscape($_group->getName()); ?>
        <a href="<?php echo $_group->getHomeUrl() ?>" title="<?php echo $storeName; ?>" class="flag-link">
        <?php if ($flagSrc): ?>
            <img src="<?php echo $flagSrc;?>" alt="<?php echo $storeName;?>"/>
        <?php else: ?>
            <span><?php echo substr($storeName, 0, 3);?></span>
        <?php endif;?>
        </a>
    <?php endforeach; ?>
</div>
<?php endif; ?>
